name: Ruby Setup Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_ruby:
    runs-on: ubuntu-24.04-x64
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev
        
    - name: Install ruby-build
      run: |
        git clone https://github.com/rbenv/ruby-build.git
        cd ruby-build
        sudo ./install.sh
    
    - name: Install Ruby 3.2.2
      run: |
        ruby-build 3.2.2 /opt/hostedtoolcache/Ruby/3.2.2/x64

    - name: Mark Ruby installation as complete
      run: touch /opt/hostedtoolcache/Ruby/3.2.2/x64.complete

